

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;

public class YourFilter implements Filter {
    
    public void doFilter(ServletRequest request, ServletResponse response,
            FilterChain chain)
            throws IOException, ServletException {
        
System.out.println("MyFilter invoked, invoking next resource...");
PrintWriter out=response.getWriter();
out.println("<b> It is generated by Myfilter. <br> </b>");
chain.doFilter(request,response);
System.out.println("MyFilter received control from the next resource, ending post processing...");
out.println("<br> It is appended by myfilter.");
    } 
    public void destroy() { 
        
    }
    public void init(FilterConfig filterConfig) {        
            }

       }


