package mypack;

import javax.servlet.*;
import org.apache.struts2.ServletActionContext;
import com.opensymphony.xwork2.*;
import java.io.PrintWriter;
public class MyResult implements Result {
private String page1;

public static final String DEFAULT_PARAM="page1";

	public void execute(ActionInvocation ai) throws Exception {
	ServletResponse response=ServletActionContext.getResponse();
        response.setContentType("text/html");
        ServletRequest request=ServletActionContext.getRequest();
        RequestDispatcher rd=request.getRequestDispatcher(page1);
        rd.include(request,response);
        PrintWriter out=response.getWriter(); 
        out.println( "<br><br> <font size =10 color=red> This output is generated by a struts2 result </font> <br>");
 out.println(" Action or interceptor suggested following jsp for result"+page1);
        //try{ Thread.sleep(5000); } catch(Exception e){}
        out.close();
 	}
	public void setPage1(String page) {
		this.page1 = page;
	}
}




// 1.1  value of DEFAULT_PARAM static final String constant 
// is obtained to find out name of setter method 
//to inject  page name

// 1.2 setter method identified in last step is invoked and URL of page is
//  provided to result.

// 1.3  Result is asked to get the view generated









