package com.addiittya;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.Filter;
import javax.servlet.FilterChain;
import javax.servlet.FilterConfig;
import javax.servlet.ServletException;
import javax.servlet.ServletRequest;
import javax.servlet.ServletResponse;

public class YourFilter implements Filter
{
	public void doFilter(ServletRequest request,ServletResponse response,FilterChain chain) throws ServletException,IOException
	{
		System.out.println("Filter #2 Pre");
		PrintWriter out=response.getWriter();
		out.println("Filter #2<br/>");
		out.println("Generated by YourFilter.<br/>");
		chain.doFilter(request,response);
		System.out.println("Filter #2 Post");
		out.println("Appended by YourFilter.");
		out.close();
	}
	public void init(FilterConfig config){}
	public void destroy(){}
}